/**
 * fms
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ComplianceInvoiceDetailsDto { 
    id?: number;
    hsn?: string;
    complianceQty?: number;
    compliancePrice?: number;
    sacCode?: number;
    agentQty?: number;
    agentCost?: number;
    complianceGst?: number;
    invoiceGst?: number;
    invoiceAmount?: number;
    invoiceType?: string;
    modeOfPayment?: string;
    invoiceNumber?: string;
    invoiceDate?: string;
    fromDate?: string;
    toDate?: string;
    companyName?: string;
    invoiceAttachment?: string;
    invoiceApprovalComment?: string;
    vendorId?: string;
}