/**
 * fms
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ComplianceReportDto { 
    id?: number;
    serviceId?: string;
    createdOn?: Date;
    currentStage?: string;
    updatedOn?: Date;
    registrationNumber?: string;
    manufacturer?: string;
    model?: string;
    isVehicleOffRoad?: number;
    vendorId?: string;
    vendorName?: string;
    typeOfCompliance?: string;
    renewalFees?: number;
    agentFees?: number;
    miscAmount?: number;
    penaltyFees?: number;
    gstAmount?: number;
    finalAmount?: number;
    quotationAttachment?: string;
    overallComment?: string;
    hub?: string;
    branch?: string;
    zone?: string;
    region?: string;
    invoiceType?: string;
    modeOfPayment?: string;
    invoiceNumber?: string;
    invoiceDate?: string;
    invoiceAmount?: number;
    fromDate?: string;
    toDate?: string;
    companyName?: string;
    invoiceAttachment?: string;
    rejectionComment?: string;
    utrNumber?: string;
    paymentDate?: string;
    isAdvanceRequired?: number;
    isInvoiceUploaded?: number;
    isRejected?: number;
    isClosed?: number;
    status?: string;
}