/**
 * fms
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CreateBatteryRequestDto { 
    zone?: string;
    region?: string;
    branch?: string;
    hub?: string;
    registrationNumber?: string;
    vehicleAge?: string;
    manufacturer?: string;
    model?: string;
    vehicleSubStatus?: string;
    isVehicleOffRoad?: number;
    offRoadReason?: string;
    offRoadStatusChangeDate?: string;
    battery_Serial_Number?: string;
    typed_Serial_Number?: string;
    battery_Make?: string;
    battery_Model?: string;
    battery_Invoice_Date?: string;
    battery_Warranty?: number;
    battery_Vendor_Name?: string;
    battery_Cost?: number;
    battery_Age?: number;
    battery_Scrap_Value?: number;
    new_Battery_Make?: string;
    new_Battery_Model?: string;
    new_Battery_VendorId?: string;
    new_Battery_Cost?: number;
    new_Battery_GST?: number;
    new_Battery_Estimated_Cost?: number;
    current_Battery_Serial_Number?: string;
    quotationAttachment?: string;
    isAdvanceRequired?: number;
    advanceAmount?: number;
    overallComment?: string;
    isRMApprovalRequired?: number;
    isNFMApprovalRequired?: number;
    isZMApprovalRequired?: number;
    isVPApprovalRequired?: number;
    currentStage?: string;
}