/**
 * fms
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MaintenanceReportDto { 
    id?: number;
    serviceId?: string;
    createdOn?: Date;
    currentStage?: string;
    updatedOn?: Date;
    isVehicleOffRoad?: number;
    registrationNumber?: string;
    dateOfLastService?: string;
    serviceRequestType?: string;
    vendorId?: string;
    vendorName?: string;
    quotationAttachment?: string;
    totalEstimatedCost?: number;
    overallComment?: string;
    invoiceTotalEstimatedCost?: number;
    serviceDate?: string;
    jobcardAttachment?: string;
    invoiceAttachment?: string;
    modeOfPayment?: string;
    invoiceDate?: string;
    invoiceNumber?: string;
    hub?: string;
    branch?: string;
    zone?: string;
    region?: string;
    invoiceType?: string;
    rejectionComment?: string;
    manufacturer?: string;
    model?: string;
    utrNumber?: string;
    paymentDate?: string;
    isAdvanceRequired?: number;
    isInvoiceUploaded?: number;
    isRejected?: number;
    isClosed?: number;
    status?: string;
}