/**
 * fms
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TicketDetailsDto { 
    id?: number;
    zone?: string;
    region?: string;
    hub?: string;
    branch?: string;
    registrationNumber?: string;
    vehicleAge?: string;
    manufacturer?: string;
    model?: string;
    vehicleSubStatus?: string;
    isVehicleOffRoad?: number;
    dateOfLastService?: string;
    offRoadReason?: string;
    offRoadStatusChangeDate?: string;
    serviceRequestType?: string;
    vendorName?: string;
    totalSpareCost?: number;
    totalLaborCost?: number;
    totalEstimatedCost?: number;
    quotationAttachment?: string;
    componentDetails?: string;
    overallComment?: string;
    isAdvanceRequired?: number;
    advanceAmount?: number;
    status?: string;
    hasFSMApproved?: number;
    fsmApprovedById?: number;
    fsmApprovalTimestamp?: string;
    fsmApprovalComment?: string;
    fsmApprovalAttachment?: string;
    isHFMApprovalRequired?: number;
    hasHFMApproved?: number;
    hfmApprovedById?: number;
    hfmApprovalTimestamp?: string;
    hfmApprovalComment?: string;
    hfmApprovalAttachment?: string;
    isRMApprovalRequired?: number;
    hasRMApproved?: number;
    rmApprovedById?: number;
    rmApprovalTimestamp?: string;
    rmApprovalComment?: string;
    rmApprovalAttachment?: string;
    isNFMApprovalRequired?: number;
    hasNFMApproved?: number;
    nfmApprovedById?: number;
    nfmApprovalTimestamp?: string;
    nfmApprovalComment?: string;
    nfmApprovalAttachment?: string;
    isZMApprovalRequired?: number;
    hasZMApproved?: number;
    zmApprovedById?: number;
    zmApprovalTimestamp?: string;
    zmApprovalComment?: string;
    zmApprovalAttachment?: string;
    isVPApprovalRequired?: number;
    hasVPApproved?: number;
    vpApprovedById?: number;
    vpApprovalTimestamp?: string;
    vpApprovalComment?: string;
    vpApprovalAttachment?: string;
    isRejected?: number;
    rejectedById?: number;
    rejectionComment?: string;
    rejectionTimestamp?: string;
    hasAdvanceApproved?: number;
    advanceApprovedById?: number;
    advanceApprovalTimestamp?: string;
    advanceApprovalComment?: string;
    advanceApprovalAttachment?: string;
    isInvoiceUploaded?: number;
    invoiceAttachment?: string;
    invoiceUploadedBy?: number;
    invoiceUploadedAt?: string;
    hasFinanceUserApproved?: number;
    financeApprovedById?: number;
    financeApprovalTimestamp?: string;
    financeApprovalComment?: string;
    financeApprovalAttachment?: string;
    allApprovalStagesCompleted?: number;
    currentStage?: string;
    createdOn?: string;
    createdById?: number;
    updatedOn?: string;
    updatedBy?: number;
}