/**
 * fms
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TicketsForDashboardDto { 
    id?: number;
    zone?: string;
    region?: string;
    branch?: string;
    hub?: string;
    registrationNumber?: string;
    manufacturer?: string;
    model?: string;
    isVehicleOffRoad?: number;
    totalEstimatedCost?: number;
    isAdvanceRequired?: number;
    hasAdvanceApproved?: number;
    hasFinanceUserApproved?: number;
    status?: string;
    createdOn?: Date;
    currentStage?: string;
}