/**
 * fms
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TyreReportDto { 
    id?: number;
    serviceId?: string;
    createdOn?: Date;
    currentStage?: string;
    updatedOn?: Date;
    isVehicleOffRoad?: number;
    registrationNumber?: string;
    selectedVendorId?: string;
    selectedVendorName?: string;
    quotationAttachment?: string;
    modeOfPayment?: string;
    estimatedTyreCost?: number;
    estimatedTyreGst?: number;
    tyreQuantity?: number;
    estimatedTyreTotal?: number;
    selectedTyre1Manufacturer?: string;
    selectedTyre1FitmentDate?: string;
    selectedTyre2Manufacturer?: string;
    selectedTyre2FitmentDate?: string;
    selectedTyre3Manufacturer?: string;
    selectedTyre3FitmentDate?: string;
    selectedTyre4Manufacturer?: string;
    selectedTyre4FitmentDate?: string;
    selectedTyre5Manufacturer?: string;
    selectedTyre5FitmentDate?: string;
    invoiceTotal?: number;
    actualTyreVendorId?: string;
    actualTyreVendorName?: string;
    hub?: string;
    branch?: string;
    zone?: string;
    region?: string;
    overallComment?: string;
    invoiceAttachment?: string;
    invoiceDate?: string;
    invoiceNumber?: string;
    companyName?: string;
    invoiceType?: string;
    rejectionComment?: string;
    utrNumber?: string;
    paymentDate?: string;
    isAdvanceRequired?: number;
    isInvoiceUploaded?: number;
    isRejected?: number;
    isClosed?: number;
    status?: string;
}