/**
 * fms
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TyreInvoiceDetails { 
    id?: number;
    newTyre1Manufacturer?: string;
    newTyre1Model?: string;
    newTyre1Type?: string;
    newTyre1Size?: string;
    newTyre1Cost?: number;
    newTyre1FitmentDate?: string;
    newTyre1SerialNumber?: string;
    newTyre2Manufacturer?: string;
    newTyre2Model?: string;
    newTyre2Type?: string;
    newTyre2Size?: string;
    newTyre2Cost?: number;
    newTyre2FitmentDate?: string;
    newTyre2SerialNumber?: string;
    newTyre3Manufacturer?: string;
    newTyre3Model?: string;
    newTyre3Type?: string;
    newTyre3Size?: string;
    newTyre3Cost?: number;
    newTyre3FitmentDate?: string;
    newTyre3SerialNumber?: string;
    newTyre4Manufacturer?: string;
    newTyre4Model?: string;
    newTyre4Type?: string;
    newTyre4Size?: string;
    newTyre4Cost?: number;
    newTyre4FitmentDate?: string;
    newTyre4SerialNumber?: string;
    newTyre5Manufacturer?: string;
    newTyre5Model?: string;
    newTyre5Type?: string;
    newTyre5Size?: string;
    newTyre5Cost?: number;
    newTyre5FitmentDate?: string;
    newTyre5SerialNumber?: string;
    actualTyreVendorId?: string;
    actualTyreCost?: number;
    actualTyreTotal?: number;
    actualTyreGst?: number;
    laborCost?: number;
    laborGst?: number;
    laborQuantity?: number;
    invoiceTotal?: number;
    invoiceDate?: string;
    invoiceNumber?: string;
    invoiceType?: string;
    companyName?: string;
    hsn?: string;
    modeOfPayment?: string;
    sacCode?: number;
    invoiceAttachment?: string;
    isAdvanceRequired?: number;
    advanceAmount?: number;
    tyreQuantity?: number;
    tyre1Models?: Array<string>;
    tyre2Models?: Array<string>;
    tyre3Models?: Array<string>;
    tyre4Models?: Array<string>;
    tyre5Models?: Array<string>;
    grandTotal?: number;
}