/**
 * fms
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UpdateTyreRequestDto { 
    id?: number;
    zone?: string;
    region?: string;
    branch?: string;
    hub?: string;
    registrationNumber?: string;
    vehicleAge?: string;
    manufacturer?: string;
    model?: string;
    vehicleSubStatus?: string;
    isVehicleOffRoad?: number;
    offRoadReason?: string;
    offRoadStatusChangeDate?: string;
    tyreQty?: number;
    selectedTyre1SerialNumber?: string;
    typedTyre1SerialNumber?: string;
    selectedTyre1Manufacturer?: string;
    selectedTyre1Model?: string;
    selectedTyre1Size?: string;
    selectedTyre1FitmentDate?: string;
    tyre1Attachment?: string;
    selectedTyre2SerialNumber?: string;
    typedTyre2SerialNumber?: string;
    selectedTyre2Manufacturer?: string;
    selectedTyre2Model?: string;
    selectedTyre2Size?: string;
    selectedTyre2FitmentDate?: string;
    tyre2Attachment?: string;
    selectedTyre3SerialNumber?: string;
    typedTyre3SerialNumber?: string;
    selectedTyre3Manufacturer?: string;
    selectedTyre3Model?: string;
    selectedTyre3Size?: string;
    selectedTyre3FitmentDate?: string;
    tyre3Attachment?: string;
    selectedTyre4SerialNumber?: string;
    typedTyre4SerialNumber?: string;
    selectedTyre4Manufacturer?: string;
    selectedTyre4Model?: string;
    selectedTyre4Size?: string;
    selectedTyre4FitmentDate?: string;
    tyre4Attachment?: string;
    selectedTyre5SerialNumber?: string;
    typedTyre5SerialNumber?: string;
    selectedTyre5Manufacturer?: string;
    selectedTyre5Model?: string;
    selectedTyre5Size?: string;
    selectedTyre5FitmentDate?: string;
    tyre5Attachment?: string;
    estimatedTyreCost?: number;
    estimatedTyreGst?: number;
    estimatedTyreTotal?: number;
    selectedVendorId?: string;
    quotationAttachment?: string;
    isAdvanceRequired?: number;
    advanceAmount?: number;
    overallComment?: string;
    isRMApprovalRequired?: number;
    isNFMApprovalRequired?: number;
    isZMApprovalRequired?: number;
    isVPApprovalRequired?: number;
    currentStage?: string;
    createdOn?: Date;
}