/**
 * fms
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Vehicle { 
    registration_No?: string;
    asset_Type?: string;
    manufacturer?: string;
    model_Name?: string;
    registration_Date?: string;
    owner_Name?: string;
    off_Road?: string;
    vehicleSubStatus?: string;
    standBy_FromDate?: string;
    standBy_ToDate?: string;
    onRoute_FromDate?: string;
    onRoute_ToDate?: string;
    offroad_Date?: string;
    offroad_ToDate?: string;
    offroad_Reason?: string;
    zone_Name?: string;
    region_Name?: string;
    hub_Name?: string;
    branch_Name?: string;
    safety_Triangle?: string;
    make_Year?: string;
    jack_And_Lever?: string;
    mha_Compliant?: string;
    bS_Norms?: string;
    toolkit?: string;
    dcv?: string;
    first_Aid?: string;
    addedOn?: Date;
    modifiedOn?: Date;
}