/**
 * fms
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface VehicleForDashboard { 
    registration_No?: string;
    chassis_Number?: string;
    manufacturer?: string;
    model?: string;
    current_Km_Run?: string;
    is_Vehicle_Offroad?: string;
    asset_type?: string;
    registration_Date?: string;
    active?: string;
    addedOn?: Date;
    modifiedOn?: Date;
}