/**
 * fms
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Vendor { 
    id?: string;
    name?: string;
    city?: string;
    state_Code?: string;
    contact?: string;
    phone_Number?: string;
    pan?: string;
    gsT_NO?: string;
    addedOn?: Date;
    modifiedOn?: Date;
}