export * from './admin.service';
import { AdminService } from './admin.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './batteryRequest.service';
import { BatteryRequestService } from './batteryRequest.service';
export * from './bulkUpload.service';
import { BulkUploadService } from './bulkUpload.service';
export * from './complianceRequest.service';
import { ComplianceRequestService } from './complianceRequest.service';
export * from './databaseManagement.service';
import { DatabaseManagementService } from './databaseManagement.service';
export * from './maintenanceRequest.service';
import { MaintenanceRequestService } from './maintenanceRequest.service';
export * from './transaction.service';
import { TransactionService } from './transaction.service';
export * from './tyreRequest.service';
import { TyreRequestService } from './tyreRequest.service';
export const APIS = [AdminService, AuthService, BatteryRequestService, BulkUploadService, ComplianceRequestService, DatabaseManagementService, MaintenanceRequestService, TransactionService, TyreRequestService];
