/**
 * fms
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { History } from '../model/history';
import { SystemAndPart } from '../model/systemAndPart';
import { Vehicle } from '../model/vehicle';
import { Vendor } from '../model/vendor';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class BulkUploadService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param File 
     * @param FileType 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public bulkUploadCSVFilePostForm(File?: Blob, FileType?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public bulkUploadCSVFilePostForm(File?: Blob, FileType?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public bulkUploadCSVFilePostForm(File?: Blob, FileType?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public bulkUploadCSVFilePostForm(File?: Blob, FileType?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'multipart/form-data'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): void; };
        let useForm = false;
        let convertFormParamsToString = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        // see https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        }

        if (File !== undefined) {
            formParams = formParams.append('File', <any>File) as any || formParams;
        }
        if (FileType !== undefined) {
            formParams = formParams.append('FileType', <any>FileType) as any || formParams;
        }

        return this.httpClient.request<any>('post',`${this.basePath}/BulkUpload/CSVFile`,
            {
                body: convertFormParamsToString ? formParams.toString() : formParams,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public bulkUploadGetSystemAndPartMasterGet(observe?: 'body', reportProgress?: boolean): Observable<Array<SystemAndPart>>;
    public bulkUploadGetSystemAndPartMasterGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<SystemAndPart>>>;
    public bulkUploadGetSystemAndPartMasterGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<SystemAndPart>>>;
    public bulkUploadGetSystemAndPartMasterGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<SystemAndPart>>('get',`${this.basePath}/BulkUpload/GetSystemAndPartMaster`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public bulkUploadGetUploadHistoryGet(observe?: 'body', reportProgress?: boolean): Observable<Array<History>>;
    public bulkUploadGetUploadHistoryGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<History>>>;
    public bulkUploadGetUploadHistoryGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<History>>>;
    public bulkUploadGetUploadHistoryGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<History>>('get',`${this.basePath}/BulkUpload/GetUploadHistory`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public bulkUploadGetVehicleMasterGet(observe?: 'body', reportProgress?: boolean): Observable<Array<Vehicle>>;
    public bulkUploadGetVehicleMasterGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Vehicle>>>;
    public bulkUploadGetVehicleMasterGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Vehicle>>>;
    public bulkUploadGetVehicleMasterGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Vehicle>>('get',`${this.basePath}/BulkUpload/GetVehicleMaster`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public bulkUploadGetVendorMasterGet(observe?: 'body', reportProgress?: boolean): Observable<Array<Vendor>>;
    public bulkUploadGetVendorMasterGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Vendor>>>;
    public bulkUploadGetVendorMasterGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Vendor>>>;
    public bulkUploadGetVendorMasterGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Vendor>>('get',`${this.basePath}/BulkUpload/GetVendorMaster`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
